### ISSUE TITLE
UX Issues with the select function

### ISSUE THREAD

**Issue by RubenWaterman** [elixir-cldr/cldr_html#11]
First of all, thanks for the efforts, it makes a country selector way easier :)! I just had two comments on the select user experience:

- When a prompt is added (i.e. `prompt: "Select your country 🌎"`), the first territory (in case all countries are used, Afghanistan) is shown, instead of the prompt. I would expect the prompt to be shown (at present, the prompt is only shown once you open the dropdown).
- If the default mapper is used, the user cannot start typing their country in order to select their country and are forced to click on the dropdown and scroll to their country. If you change the mapper to `mapper: &({&1.name <> " " <> &1.flag, &1.territory_code})` it works so the problem seems to be having the flags before the country name?

**Comment by kipcole9** [comment]
@RubenWaterman, glad you find it useful.  I hadn't actually done any real UX testing/evaluation - just testing that correctly formed HTML is generated. I've not build a super small Phoenix app to look at the UX, so thanks for the prompt.  So far I'm not seeing the same thing as you - but I have only tried on Mac Safari and Mac Chrome so far.  Here is what I'm seeing from what I generate:

## Example 1: Limited set of countries, one selected, with prompt:
```elixir
  Cldr.HTML.Territory.select(
     :my_form,
     :territory,
     territories: [:US, :AU, :HK],
     selected: :AU,
     prompt: "My Prompt"
   )
```
#### No selection - straight after page refresh
<img width="197" alt="image" src="https://user-images.githubusercontent.com/15895/134755467-c58a12bb-8fcf-4392-9626-98f5643156cd.png">

#### Selecting - shows prompt and selection
<img width="197" alt="image" src="https://user-images.githubusercontent.com/15895/134755525-438adade-0764-495b-9886-b0a270a005a3.jpg">

## Example 2: All countries, no selection, with prompt
```elixir
<%=
  Cldr.HTML.Territory.select(
     :my_form,
     :territory,
     prompt: "Select a territory"
   )
%>
```
#### No selection - straight after page refresh
<img width="289" alt="image" src="https://user-images.githubusercontent.com/15895/134755597-128e3ceb-6348-45bb-8301-00b9eea66698.png">

#### Selecting - shows prompt
<img width="289" alt="image" src="https://user-images.githubusercontent.com/15895/134755689-043cef73-af5d-43d2-a9f8-24127abb528d.jpg">

I appreciate this is only part of what you raised - showing the prompt. I'll also look at selection with the keyboard but I suspect you are right and that selection only works by matching characters left to right.

**Comment by kipcole9** [comment]
Confirmed your suspicion that the flag prefix interfere with keyboard entry. Well, actually it doesn't interfere but it definitely doesn't behave as a user expects.

Given that others may depend on the existing default behaviour I am reluctant to change the default mapper. I think that right strategy is the one you are using - use your own mapping function.

**Comment by RubenWaterman** [comment]
> @RubenWaterman, glad you find it useful. I hadn't actually done any real UX testing/evaluation - just testing that correctly formed HTML is generated. I've now build a super small Phoenix app to look at the UX, so thanks for the prompt. So far I'm not seeing the same thing as you - but I have only tried on Mac Safari and Mac Chrome so far. Here is what I'm seeing from what I generate:
> ## Example 1: Limited set of territories, one selected, with prompt:
> 
> ```elixir
>   Cldr.HTML.Territory.select(
>      :my_form,
>      :territory,
>      territories: [:US, :AU, :HK],
>      selected: :AU,
>      prompt: "My Prompt"
>    )
> ```
> 
> #### No selection - straight after page refresh
> 
> <img alt="image" width="197" src="https://user-images.githubusercontent.com/15895/134755467-c58a12bb-8fcf-4392-9626-98f5643156cd.png">
> #### Selecting - shows prompt and selection
> 
> <img alt="image" width="197" src="https://user-images.githubusercontent.com/15895/134755525-438adade-0764-495b-9886-b0a270a005a3.jpg">
> ## Example 2: All territories, no selection, with prompt
> 
> ```elixir
> <%=
>   Cldr.HTML.Territory.select(
>      :my_form,
>      :territory,
>      prompt: "Select a territory"
>    )
> %>
> ```
> 
> #### No selection - straight after page refresh
> 
> <img alt="image" width="289" src="https://user-images.githubusercontent.com/15895/134755597-128e3ceb-6348-45bb-8301-00b9eea66698.png">
> #### Selecting - shows prompt
> 
> <img alt="image" width="289" src="https://user-images.githubusercontent.com/15895/134755689-043cef73-af5d-43d2-a9f8-24127abb528d.jpg">
> 
> I appreciate this is only part of what you raised - showing the prompt. I'll also look at selection with the keyboard but I suspect you are right and that selection only works by matching characters left to right.

My bad, I must have messed up something as now when I'm trying to do it again, I have the same output as you so I cannot reproduce my own issue... Sorry about that! Thanks again for the package, it's really useful!

**Comment by kipcole9** [comment]
I hope I didn’t sound too abrupt!  I don’t doubt what you were seeing, I am just currently unable to reproduce what you saw.  If you have some example code, or a screen shot, I’n perfectly fine to dig deeper to work out why you are getting the results you saw!
